
// This file was auto-generated by ML.NET Model Builder. 

using ClassificationWithModelBuilder;

string userInput = string.Empty;

while (!string.Equals(userInput, "No", StringComparison.CurrentCultureIgnoreCase))
{

    Console.WriteLine("Please fill in patients details to get disorder prediction.");

    Console.WriteLine($"Gender:");
    string gender = Console.ReadLine();
    Console.WriteLine($"Age:");
    float.TryParse(Console.ReadLine(), out float age);
    Console.WriteLine($"Occupation:");
    string occupation = Console.ReadLine();
    Console.WriteLine($"Sleep_Duration:");
    float.TryParse(Console.ReadLine(), out float sleep_Duration);
    Console.WriteLine($"Quality_of_Sleep (0-10):");
    float.TryParse(Console.ReadLine(), out float quality_of_Sleep);
    Console.WriteLine($"Physical_Activity_Level (0-100):");
    float.TryParse(Console.ReadLine(), out float physical_Activity_Level);
    Console.WriteLine($"Stress_Level (0-10):");
    float.TryParse(Console.ReadLine(), out float stress_Level);
    Console.WriteLine($"BMI_Category (Normal/Overweight/Obese):");
    string BMI_Category = Console.ReadLine();

    Classifier.ModelInput sampleData = new Classifier.ModelInput()
    {
        Gender = gender,
        Age = age,
        Occupation = occupation,
        Sleep_Duration = sleep_Duration,
        Quality_of_Sleep = quality_of_Sleep,
        Physical_Activity_Level = physical_Activity_Level,
        Stress_Level = stress_Level,
        BMI_Category = BMI_Category,
    };
    
    Classifier.ModelOutput predictionResult = Classifier.Predict(sampleData);
    Console.WriteLine("The patient's sleep disorder is:" + predictionResult.PredictedLabel);

    Console.WriteLine("Would you like to continue? (Type 'No' to exit)");
    userInput = Console.ReadLine();
}

